### PR TITLE
Adding logo files

### PR DESCRIPTION
**Pull request by gonuke**

### CODE REVIEW

**Comment by makeclean** [comment]
Ready to go?

**Comment by gonuke** [comment]
yes - this just adds it to the repo for use - it doesn't change the website (yet)

**Comment by gonuke** [comment]
ping @makeclean @Pshriwise @ljacobson64

**Comment by Pshriwise** [comment]
Was about to merge...don't have permission to do so for this repo.

**Comment by ljacobson64** [comment]
Looks good

**Pull request merged**
